In [1]:
import numpy as np

# Create a 3x3x3 array with random values 

In [2]:
np.random.rand(3,3,3)

array([[[0.74130255, 0.27483031, 0.5485592 ],
        [0.30011497, 0.62950599, 0.56819769],
        [0.85648504, 0.7916117 , 0.52983828]],

       [[0.66463978, 0.99332896, 0.53749428],
        [0.11691941, 0.2486677 , 0.14532961],
        [0.94410082, 0.51059808, 0.36199316]],

       [[0.83249447, 0.39378075, 0.49593938],
        [0.4858531 , 0.89253457, 0.38259165],
        [0.83149983, 0.19232472, 0.15059583]]])

# Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
p = np.diag(1+np.arange(4), k=-1)
print(p)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# Create a 8x8 matrix and fill it with a checkerboard pattern

In [4]:
q = np.tile(np.array([[0,1],[1,0]]), (4,4))
print(q)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# Normalize a 5x5 random matrix

In [5]:
arr = np.random.random((5,5))
narr = (arr - np.mean(arr)) / (np.std(arr))
print(narr)

[[-0.01075481 -0.01365951 -0.27199365  0.82156067  1.51654927]
 [-0.00334514  0.42318693 -1.57373209 -1.87536223 -1.55089653]
 [-1.26067285  0.34342653  0.04439678  1.30761322  0.05028035]
 [-0.41318403  0.27613427  0.28863385  1.08549515  1.79331777]
 [-0.38603419 -1.87379743  1.23844309  0.14832173 -0.10392715]]


#  How to find common values between two arrays?

In [6]:
a1 = np.random.randint(0,10,50)
a2 = np.random.randint(0,10,50)
print(np.intersect1d(a1,a2))

[0 1 2 3 4 5 6 7 8 9]


# How to get the dates of yesterday, today and tomorrow?

In [15]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2020-08-09 2020-08-10 2020-08-11


# Consider two random array A and B, check if they are equal

In [17]:
a1 = np.random.randint(0,5,5)
a2 = np.random.randint(0,5,5)
print(np.array_equal(a1,a2))

False


# Create random vector of size 10 and replace the maximum value by 0 

In [18]:
v = np.random.rand(10)
v[v.argmax()] = 0
print(v)

[0.65569022 0.32661675 0.29207176 0.         0.52803541 0.00459607
 0.21497872 0.03901052 0.51049141 0.72298925]


# How to print all the values of an array?

In [20]:
arr = np.ones((5, 5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


# Subtract the mean of each row of a matrix

In [28]:
arr = np.random.randn(5, 5)
print("before\n", arr)
arr = arr - np.mean(arr,axis=1)
print("\nafter\n", arr)

before
 [[ 0.17879927  2.44397401  0.04942671  1.34447249 -1.49151281]
 [ 0.92929451 -1.114266    0.12578799 -0.0177634  -0.81358931]
 [ 1.67653149  0.06826263  0.45417152 -1.08900655 -1.47141513]
 [-0.49171216  2.12733681  1.6928174   0.16906271  0.09266821]
 [ 0.71542588  0.15511029  1.11472649 -0.7238645  -0.5022018 ]]

after
 [[-0.32623266  2.62208125  0.12171792  0.62643789 -1.64335208]
 [ 0.42426258 -0.93615875  0.1980792  -0.735798   -0.96542858]
 [ 1.17149955  0.24636987  0.52646273 -1.80704115 -1.6232544 ]
 [-0.99674409  2.30544405  1.76510861 -0.54897188 -0.05917106]
 [ 0.21039394  0.33321753  1.1870177  -1.44189909 -0.65404107]]


# Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [30]:
arr1= np.random.randint(0,5,10)
print(arr1)
arr2= np.random.randint(0,8,10)
print (arr2)

[4 4 3 3 4 2 1 0 1 4]
[3 7 0 7 5 5 4 0 7 5]


In [31]:
arr1 += np.bincount(arr2, minlength=len(arr1))
print (arr1)

[6 4 3 4 5 5 1 3 1 4]


# How to get the diagonal of a dot product?

In [32]:
x = np.random.randint(0,10,(3,3))
print(x)
y = np.random.randint(0,10,(3,3))
print(y)
print("Diagonal of a dot product")
print (np.diag(np.dot(x,y)))

[[4 5 7]
 [1 9 4]
 [6 7 8]]
[[1 0 4]
 [2 0 5]
 [4 0 3]]
Diagonal of a dot product
[42  0 83]


# How to find the most frequent value in an array?

In [34]:
arr = np.random.randint(0,10,30)
print(arr)
print(np.bincount(arr).argmax())

[1 8 8 1 9 5 7 2 9 9 3 9 8 1 5 4 0 9 8 1 6 4 8 8 4 8 0 1 6 6]
8


# How to get the n largest values of an array

In [35]:
arr = np.random.randint(0,10,50)
np.bincount(arr).argmax()

2

# How to create a record array from a regular array?

In [36]:
x = np.array([("Hello", 123, 3),
              ("World", 306, 2)])
rec = np.core.records.fromarrays(x.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')

print (rec)

[(b'Hello', 123., 3) (b'World', 306., 2)]
